repositories {

    mavenLocal()

    maven {
        name = 'spigotmc-repo'
        url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/'
    }

    maven {
        name = "Minecraft Libraries"
        url = "https://libraries.minecraft.net"
    }

}

dependencies {
    // servers
    compileOnly 'net.md-5:bungeecord-api:1.21-R0.4'
    compileOnly 'org.spigotmc:spigot-api:1.21.11-R0.1-SNAPSHOT'

    // adventure API (https://docs.adventure.kyori.net/)
    compileOnly "net.kyori:adventure-api:4.+"
    compileOnly "net.kyori:adventure-text-serializer-legacy:4.+"
    compileOnly "net.kyori:adventure-text-minimessage:4.+"

    // log4j
    compileOnly 'org.apache.logging.log4j:log4j-api:2.+'
    compileOnly 'org.apache.logging.log4j:log4j-core:2.+'
    compileOnly 'net.luckperms:api:5.+'

    // general libs
    implementation 'org.jetbrains:annotations:26.+'
    implementation 'com.google.code.gson:gson:2.+'

}

shadowJar {
    relocate 'org.intellij.lang.annotations', 'net.cybercake.cyberapi.dependencies.intellij.annotations'
    relocate 'org.jetbrains.annotations', 'net.cybercake.cyberapi.dependencies.jetbrains.annotations'
    relocate 'com.google.gson', 'net.cybercake.cyberapi.dependencies.google.gson'
}