name: CyberAPI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
 
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17]
      fail-fast: true
    permissions:
      contents: write
      packages: write
    steps:
      - name: Actions Checkout
        uses: actions/checkout@v3.0.2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3.3.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'gradle'
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Set Gradle Version
        uses: gradle/gradle-build-action@v2.2.0
        with:
          gradle-version: release-candidate
      - name: Build Gradle
        uses: gradle/gradle-build-action@v2.2.0
        with:
          arguments: shadowJar --stacktrace
      - name: Read Version
        id: version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: 'build/spigot-build.properties'
          property: 'version'
      - name: Read Build Number
        id: build
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: 'build/spigot-build.properties'
          property: 'buildNumber'
      - name: Release CyberAPI
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: "build/artifacts/*.jar"
          name: Version ${{ steps.version.outputs.value }}
          tag: v${{ steps.version.outputs.value }}-${{ steps.build.outputs.value }}
          body: |
            **It is not recommended you download the files from here, please use the [README's download link](https://github.com/CyberedCake/CyberAPI#how-to-install-and-use=)**
          generateReleaseNotes: true
