name: CyberAPI Pull Request Check

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17]
      fail-fast: true
    permissions:
      contents: write
      packages: write
    steps:
      - name: Actions Checkout
        uses: actions/checkout@v3.0.2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3.3.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'gradle'
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Set Gradle Version
        uses: gradle/gradle-build-action@v2.4.2
        with:
          gradle-version: release-candidate
      - name: Build Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: shadowJar --stacktrace
